- Mark BROKEN again because the bug in RubyGems 1.8.x is still there
undefined method `name' for "daemons":String
/usr/local/www/redmine/config/../vendor/rails/railties/lib/rails/gem_dependency.rb:277:in `=='

http://rubyforge.org/tracker/index.php?func=detail&aid=29188&group_id=126&atid=575

PR:		ports/162994
Reported by:	Chris <chris@imagemetrica.com>,
		Armin Pirkovitsch <armin@frozen-zone.org>,
		Dirk Meyer <dinoex@FreeBSD.org>,
		myself
Discussed with:	miwi
Feature safe:	yes