Use INSTALL_DATA for shared libraries instead of INSTALL_PROGRAM in order to fix the build failure in graphics/xaralx:
../wxOil/compatdef.h:605: undefined reference to `malloc_usable_size'

(if the library is stripped then nm(1) shows "no symbols")

Submitted by:	vd
Reviewed by:	pav
Approved by:	Pedro Giffuni <pfgshield-freebsd@yahoo.com> (maintainer)