Markus Bäurle sent me a nice report about the configure script failing.  In his config.log I noticed a pthreads problem:
/usr/X11R6/lib/libMesaGL.so: undefined reference to `pthread_getspecific'
/usr/X11R6/lib/libMesaGL.so: undefined reference to `pthread_key_create'
/usr/X11R6/lib/libMesaGL.so: undefined reference to `pthread_setspecific'

I was not able to reproduce the problem, so I asked him to test
this patch, but have not seen a response.  However, it causes no
trouble for me.